### PR TITLE
21 fix details page shows incorrect rental status and data

### LINKED ISSUE #21: Details Page Shows Incorrect Rental Status and Data
# Details Page Shows Incorrect Rental Status and Data

## Description
The details page for a rented domain (e.g., `robertin.eth`) is showing incorrect information. Specifically, it displays the domain as “listed” when it is actually rented, and the rental data (dates, status) appear to be wrong. This raises the question of whether the details page is pulling in mocked data instead of the actual domain status.

## Steps to Reproduce
1. Go to the manage page for a domain that is already rented (e.g., `robertin.eth`).
2. Observe the “Details” section.
3. Note that the page claims the domain is listed, even though it is rented, and shows unexpected rental dates.

## Expected Behavior
- The details page should accurately reflect the domain’s current rental status (rented vs. listed).
- The rental period and expiration date displayed should match the actual data.

## Actual Behavior
- The page shows the domain as listed despite being rented.
- The displayed dates for the rental period appear to be incorrect or mocked.

## Possible Causes
- The details page may be using outdated or mocked data instead of the real rental status.
- There could be an API call or data fetching issue leading to incorrect status/dates.

Image

Image

### PR DESCRIPTION
**Pull request by edulennert**
# Details Page Shows Incorrect Rental Status and Data

## Description
The details page for a rented domain (e.g., `robertin.eth`) is showing incorrect information. Specifically, it displays the domain as “listed” when it is actually rented, and the rental data (dates, status) appear to be wrong. This raises the question of whether the details page is pulling in mocked data instead of the actual domain status.

## Steps to Reproduce
1. Go to the manage page for a domain that is already rented (e.g., `robertin.eth`).
2. Observe the “Details” section.
3. Note that the page claims the domain is listed, even though it is rented, and shows unexpected rental dates.

## Expected Behavior
- The details page should accurately reflect the domain’s current rental status (rented vs. listed).
- The rental period and expiration date displayed should match the actual data.

## Actual Behavior
- The page shows the domain as listed despite being rented.
- The displayed dates for the rental period appear to be incorrect or mocked.

## Possible Causes
- The details page may be using outdated or mocked data instead of the real rental status.
- There could be an API call or data fetching issue leading to incorrect status/dates.

Image

Image

### CODE REVIEW

File: packages/nextjs/app/manage/[slug]/page.tsx [hunk 1]
```diff
@@ -76,6 +76,8 @@ export default function RentedDomainDetails() {
     );
   }
 
+  const endTime = rental.rentals?.[0]?.endTime;
```
Comment (pikonha) [inline packages/nextjs/app/manage/[slug]/page.tsx:79]: if there are no rentals, this this code should be called

Comment (eduramme) [reply packages/nextjs/app/manage/[slug]/page.tsx:79]: @pikonha yes

**Review by pikonha — APPROVED** [review]
